@Library('Jenkins-Shared-Library') _
pipeline {
    agent any

    environment {
        GIT_CRED = credentials('GitHub_Private_Repo')  // Use the GitHub credentials ID here
        
    }

    stages {
        stage('Checkout: Clone Repository') {
            steps {
                // Clone the private GitHub repository using stored credentials
                git branch: 'main',
                    url: 'https://github.com/Macarious-GK/DevOps.git',
                    credentialsId: 'GitHub_Private_Repo'
            }
        }

        stage('Linter_Stage: Flake8 --> Syntax errors') {
            steps {
                // Run Flake8, save the output to a report, and check for fatal errors (e.g., syntax errors)
                script {
                        // Linting stage using Flake8
                        dir('App'){
                            runFlake8Linting()   
                        }                 
                }
            }
        }

        stage('SAST Stage: Bandit --> Static Security Checks') {
            steps {
                script {
                    sh '''
                    echo "Running Bandit for security checks..."
                    bandit -r . -f json -o bandit_Report.json
                    
                    
                    # Check if Bandit found any issues
                    if grep '"issue_severity":' bandit_Report.json > /dev/null; then
                        echo "Failed from SAST stage: Security issues detected by Bandit."
                        exit 1
                    else
                        echo "SAST stage passed successfully: No issues found by Bandit."
                    fi
                    '''
                }
            }
        }  

        stage('App Feature Testing: UnitTesting') {
            steps {
                dir('App') {
                    script {
                        sh '''
                        echo "Starting unit tests..."
                        python3 -m venv venv

                        # Activate virtual environment using bash
                        bash -c "source venv/bin/activate && pip install -r requirements.txt && python3 manage.py test && deactivate"
                        result=$?

                        if [ $result -eq 0 ]; then
                            echo "Unit tests passed successfully."
                        else
                            echo "Unit tests failed. Please check the test results."
                            exit 1
                        fi
                        '''
                    }
                }
            }
        }
        stage('Docker Image Build') {
            steps {
                script {

                    dir('Docker') {

                        // Build the Docker image
                        echo "Building Docker image..."
                        sh 'docker build -t macarious25siv/books:V4 .'

                        // Check the result of the build and handle errors
                        def result = sh(script: 'docker images | grep macarious25siv/books', returnStatus: true)
                        if (result == 0) {
                            echo "Docker image built successfully."
                        } else {
                            error("Docker image build failed.")
                        }
                    }
                }
            }
        }


        stage('Docker Image Scanning Stage: Snyk') {
            steps {
                script {
                    dir('Docker') {
                        // Snyk Ligon &&  Test the Docker image with Snyk
                        snykLogin('Snyk_Token_ID')
                        snykTestDockerImage('macarious25siv/books:V4')
                    }       
                }
            }
        }

        stage('Docker Hub Login & Push Image ') {
            steps {
                script {
                    // Login to Docker Hub using stored credentials, Then Push Image
                    dockerHubLogin('Docker_Creds')
                    pushDockerImage('macarious25siv/books:V4')
                }
            }
        }

        stage('Deploy on EKS'){
            steps{
                dir('K8s'){
                    withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws-jenkins-credentials', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh '''
                    aws eks update-kubeconfig --name Macarious-eks-cluster --region us-east-2
                    kubectl get svc
                    echo "Applying namespace.yaml..."
                    kubectl apply -f namespace.yaml

                    echo "Applying pv.yaml..."
                    kubectl apply -f pv.yaml

                    echo "Applying pvc.yaml..."
                    kubectl apply -f pvc.yaml

                    echo "Applying job.yaml..."
                    kubectl apply -f job.yaml

                    echo "Applying service.yaml..."
                    kubectl apply -f service.yaml

                    echo "Applying ingress.yaml..."
                    kubectl apply -f ingress.yaml

                    echo "Applying deployment.yaml..."
                    kubectl apply -f deployment.yaml

                    '''
                }

                }
                

            }
        }
    }
    
    post {
        always {
            // Clean up the workspace and logout from Docker Hub
            echo "Cleaning up the workspace and logging out from Docker Hub..."
            sh 'docker logout'
            cleanWs()
        }
    }
}